### ISSUE TITLE
Cannot import using "from claude import Claude"

### ISSUE THREAD

**Issue by fundinglife** [Nipun1212/Claude_api#1]
from claude import Claude
ImportError: cannot import name 'Claude' from 'claude'

**Comment by Nipun1212** [comment]
Hi, can you make sure you first run this command in your terminal, pip install claude2
and maybe try inside a virtual env.
I started a new virtual env and downloaded the package again, and got no import error
<img width="786" alt="image" src="https://github.com/Nipun1212/Claude_api/assets/80609104/67000535-37cc-4f8e-924c-5d72367287d6">

**Comment by Nipun1212** [comment]
hi if you still have this issue, please let me know, else I'll close this issue
